### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by josephcoombe** [metamorph-inc/openmeta-rocket#3]
See: https://github.com/metamorph-inc/openmeta-vahana

Don't forget 3rd party licenses (if any).

**Comment by caileycline** [comment]
Should I add them as separate files or all in one?

**Comment by josephcoombe** [comment]
This seems pretty reasonable: https://softwareengineering.stackexchange.com/questions/234511/what-is-the-best-practice-for-arranging-third-party-library-licenses-paperwork

A single LICENSE-3RD-PARTY.txt
