### ISSUE TITLE
openmeta-rocket.xme no Testing folder

### ISSUE THREAD

**Issue by josephcoombe** [metamorph-inc/openmeta-rocket#4]
From README:
```
## Getting Started with the OpenMETA Rocket Model
### Opening the openmeta-rocket project
1. Open the openmeta-rocket folder.
1. Double-click on the openmeta-rocket.xme file.
1. GME will open and display a pop-up 'Import to new project' window. Select 'Create
   project file' and click 'Next >'.
1. The 'Save As' window will open. Click 'Save' to save 'openmeta-rocket.mga' inside
   the openmeta-rocket folder.

### Viewing a PET model
1. Within GME, to your right, there should be a 'GME Browser' window with a single
   'RootFolder' object inside. Click on the '+' to expand the root folder.
1. Left-click on the '+' next to 'Testing' to expand the testing folder.
```

The openmeta-rocket.xme does not appear to contain a Testing Folder. I presume the correct xme is one of the others in the directory?

**Comment by caileycline** [comment]
Yes. The xme's didn't play nicely with GitHub, so there ended up being a lot of versions. I'm cleaning up the final version now and will push it soon. I'll remove the other versions then to avoid confusing people.

**Comment by josephcoombe** [comment]
Sounds good. Which version should I use for README?

**Comment by caileycline** [comment]
I just updated openmeta-rocket.xme, so that one should work now (I might update some of the names, but functionally it should be fine). I'm still working on that part of the README though. (Most of what's there now was copied from the Vahana README)
