### ISSUE TITLE
Feedback on README

### ISSUE THREAD

**Issue by adamnagel** [metamorph-inc/openmeta-rocket#6]
The README is looking good. The technical focus is a good complement to the blog post.

This section recommends downloading the wheel and test file from the repo:
https://github.com/metamorph-inc/openmeta-rocket#jpype-library
Why not simply have them clone the repo first, then they'll have these files locally?

In step 4
https://github.com/metamorph-inc/openmeta-rocket#running-a-pet-model
yellow means that the job is queued

**Comment by caileycline** [comment]
Thanks! Both issues have been fixed.
